base/urls.py
from django.urls import path
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import (
    LogoutView,
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView
)
from .views import (
        teachers_dashboard,
        students_dashboard,
        CustomLoginView,
        award_point,
        update_point,
        delete_point,
        redeem_point,
        student_points,
        student_awards,
        points_awarded,
        points_redeemed
)

urlpatterns = [
    path('teachers/dashboard/', teachers_dashboard, name='teachers_dashboard'),
    path('students/dashboard/', students_dashboard, name='students_dashboard'),
    path('', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path("award-point/", award_point, name="award-point"),
    path("redeem-point/", redeem_point, name="redeem-point"),
    path("update-point/<str:pk>/", update_point, name="update-point"),
    path("delete-point/<str:pk>/", delete_point, name="delete-point"),
    path("student-points/", student_points, name="student-points"),
    path("student-awards/", student_awards, name="student-awards"),
    path("points-awarded/", points_awarded, name="points-awarded"),
    path("points-redeemed/", points_redeemed, name="points-redeemed"),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='base/registration/password_change_form.html',
            success_url=reverse_lazy('password_change_done')
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='base/registration/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        "reset_password/",
        auth_views.PasswordResetView.as_view(
            template_name='base/registration/password_reset_form.html'
        ),
        name="reset_password"
    ),
    path(
        'password_reset_sent/',
        auth_views.PasswordResetDoneView.as_view(
            template_name='base/registration/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='base/registration/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset_password_complete/',
        PasswordResetCompleteView.as_view(
            template_name='base/registration/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
]

reward_system/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("base.urls")),
]

base/models.py
from django.db import models, transaction
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import pre_save, post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model


# Define a custom user model that extends AbstractUser
class CustomUser(AbstractUser):
    """ customizing the user model """
    # Additional fields for the custom user model
    first_name = models.CharField(max_length=30, blank=False)
    last_name = models.CharField(max_length=30, blank=False)
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # String representation of the user object, used for display purposes
    def __str__(self):
        return f"{self.first_name} {self.last_name}"


# Define a model for storing additional data related to students
class StudentProfile(models.Model):
    """ model for storing student's extra data """
    # Establish a one-to-one relationship with the CustomUser model
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE,
                                primary_key=True)
    
    # Additional fields for student-specific data
    grade = models.CharField(max_length=10, null=True, blank=True)
    adm_no = models.PositiveIntegerField(null=True, blank=True, unique=True)
    parent_contact = models.CharField(max_length=15, null=True, blank=True)

    def __str__(self):
        return self.user.username


# Define a model for storing additional data related to teachers
class TeacherProfile(models.Model):
    """ model for storing teacher's extra data """
    # Establish a one-to-one relationship with the CustomUser model
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE,
                                primary_key=True)
    
    # Additional fields for teacher-specific data
    designation = models.CharField(max_length=30, null=True, blank=True)
    reg_no = models.PositiveIntegerField(null=True, blank=True, unique=True)
    contact = models.CharField(max_length=15, null=True, blank=True)


# Signal handler to create a StudentProfile when
# a CustomUser is created and is a student
@receiver(post_save, sender=CustomUser)
def create_student_profile(sender, instance, created, **kwargs):
    """Create a StudentProfile when a CustomUser is created & is a student"""
    if created and instance.is_student:
        StudentProfile.objects.get_or_create(user=instance)


# Signal handler to save a StudentProfile when
# a CustomUser is saved and is a student
@receiver(post_save, sender=CustomUser)
def save_student_profile(sender, instance, **kwargs):
    """Save a StudentProfile when a CustomUser is saved and is a student."""
    if instance.is_student:
        student_profile, created = (
                StudentProfile.objects.get_or_create(user=instance)
        )
        if not created:
            student_profile.save()


# Signal handler to create a TeacherProfile when
# a CustomUser is created and is a teacher
@receiver(post_save, sender=CustomUser)
def create_teacher_profile(sender, instance, created, **kwargs):
    """Create a TeacherProfile when a CustomUser is created & is a teacher"""
    if created and instance.is_teacher:
        TeacherProfile.objects.create(user=instance)


# Signal handler to save a TeacherProfile when
# a CustomUser is saved and is a teacher
@receiver(post_save, sender=CustomUser)
def save_teacher_profile(sender, instance, **kwargs):
    """Save a TeacherProfile when a CustomUser is saved and is a teacher"""
    if instance.is_teacher:
        teacher_profile, created = (
                TeacherProfile.objects.get_or_create(user=instance)
        )
        if not created:
            teacher_profile.save()


class PointCategory(models.Model):
    """ Category list for awarding points """
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255)
    point = models.PositiveIntegerField(null=False, blank=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.point} pts"


class PointTransaction(models.Model):
    """ Class for awarding points to students """
    student = models.ForeignKey(
        CustomUser,
        related_name='receiving_point',
        on_delete=models.CASCADE,
        limit_choices_to={'is_student': True}
    )
    teacher = models.ForeignKey(
        CustomUser,
        related_name='giving_point',
        on_delete=models.CASCADE,
        limit_choices_to={'is_teacher': True}
    )
    category = models.ForeignKey(PointCategory, on_delete=models.CASCADE)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at', '-category']

    def __str__(self):
        return f"{self.student} - {self.category}"


# Signal handler to set the teacher field in PointTransaction before saving
@receiver(pre_save, sender=PointTransaction)
def set_teacher(sender, instance, **kwargs):
    """Set the teacher field in PointTransaction before saving"""

    # Check if the teacher_id is not set
    if not instance.teacher_id:
        # Retrieve the user model and get the current user by primary key
        current_user = get_user_model().objects.get(pk=instance.teacher_id)
        # Check if the current user is authenticated and is a teacher
        if (
            current_user and
            current_user.is_authenticated and
            current_user.is_teacher
        ):
            # Set the teacher field in PointTransaction to the current user
            instance.teacher = current_user


# Define a model for AwardItem to be redeemed by students
class AwardItem(models.Model):
    """ gifts, textbooks, trips, etc """
    name = models.CharField(max_length=100)
    points = models.IntegerField()
    description = models.TextField(null=True, blank=True)
    units = models.IntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # Specify the default ordering for queries
        ordering = ('-updated_at', '-created_at')

    # String representation of the AwardItem object, used for display purposes
    def __str__(self):
        return f"{self.name} - {self.points} points - {self.units} remaining"


class RedeemAward(models.Model):
    """ model for redeeming award """
    select_award = models.ForeignKey(
        AwardItem,
        on_delete=models.CASCADE,
        null=True,
        limit_choices_to={'units__gt': 0}
    )
    student = models.ForeignKey(
        CustomUser,
        related_name='redeeming_point',
        on_delete=models.CASCADE,
        limit_choices_to={'is_student': True}
    )
    date_redeemed = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-date_redeemed']

    def __str__(self):
        return self.select_award.name

    def save(self, *args, **kwargs):
        # Ensuring atomicity when updating both AwardItem and RedeemAward
        with transaction.atomic():
            # Deduct points from units when saving a new RedeemAward instance
            if not self.pk:  # Check if the instance is being created
                self.select_award.units -= 1
                self.select_award.save()

            super().save(*args, **kwargs)

base/forms.py
from django import forms
from django.contrib.auth.forms import (
        UserCreationForm,
        UserChangeForm,
        AuthenticationForm
)
from .models import CustomUser, PointTransaction, RedeemAward
from django.forms import ModelForm
from django.db.models import Sum


class CustomUserCreationForm(UserCreationForm):
    """ customizing user creation form """

    class Meta:
        model = CustomUser
        fields = ("username", "email")


class CustomUserChangeForm(UserChangeForm):
    """ customizing user update form """

    class Meta:
        model = CustomUser
        fields = ("username", "email")


class AwardForm(ModelForm):
    """ point award form """
    description = forms.CharField(
        label='Description',
        max_length=100,
        widget=forms.TextInput(
            attrs={
                'class': 'form-control input-sm',
                'placeholder': 'Reason for awarding the point'}
        ),
    )

    class Meta:
        model = PointTransaction
        fields = ['student', 'category', 'description']


class CustomAuthenticationForm(AuthenticationForm):
    """ authentication form """


class ReedemForm(forms.ModelForm):
    """ point award form """

    class Meta:
        model = RedeemAward
        fields = ['select_award']

        '''widgets = {
            'select_award': forms.Select(attrs={'class': 'form-control'}),
        }'''

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
        self.fields['select_award'].empty_label = 'Check available awards'

    def clean(self):
        cleaned_data = super().clean()

        if self.request:
            student = self.request.user
            total_points = (
                PointTransaction.objects.filter(student=student)
                .aggregate(Sum('category__point'))['category__point__sum'] or 0
            )
            total_redeemed = (
                RedeemAward.objects.filter(student=student)
                .aggregate(Sum('select_award__points'))
                .get('select_award__points__sum', 0) or 0
            )
            available_points = total_points - total_redeemed

            if available_points < cleaned_data.get('select_award').points:
                raise forms.ValidationError(
                        'Not enough points to redeem the award.'
                )

            cleaned_data['student'] = student

        return cleaned_data

base/templates/base/award_point.html
{% extends "base/base.html" %}

{% block title %}Award Point{% endblock %}

{% load crispy_forms_tags %}
{% block content %}
<!--< class="container custom-container">-->
<div class="container mt-3" style="width: 50%; font-size: 14px;">
  <div class="text-center">
    <h2 class="text-light">Award Point</h2>
  </div>
  <form method="POST" class="card p-3 mt-5" autocomplete="off">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-flex justify-content-between">
      <button type="submit" class="btn btn-primary">Award</button>
      <button class="btn btn-primary" onclick="goBack()">Back</button>
    </div>
  </form>
  {% for message in messages %}
  {% if message.tags == 'success' %}
  <div class="text-center alert alert-primary alert-dismissible fade show" role="alert">{{message}}
    <a href="{%url 'teachers_dashboard' %}" type="button" class="btn btn-close" data-bs-dismiss="alert"
      aria-label="Close"></a>
  </div>
  {% endif %}
  {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script>
  function goBack() {
    window.history.back();
  }
  
  $("#id_student").select2({width: '100%'});
  $("#id_category").select2({width: '100%'});
</script>
{% endblock %}

base/templates/base/base.html
<!-- templates/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'base/assets/favicon-32x32.png' %}">
  <title>{% block title %}Base{% endblock %}</title>
  <!--<link rel="stylesheet" type="text/css" href="{% static 'base/css/main.css' %}">-->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body style="background-color:hsl(248, 53%, 58%);">
  <main>
    {% block content %}
    {% endblock %}
  </main>
  {% block scripts %}
  {% endblock %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>

base/templates/base/dashboard.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'base/assets/favicon-32x32.png' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="theme-color" content="#000000" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
    <title>{% block title %}Dashboard{% endblock %}</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Inter%3A400%2C600%2C700"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Sriracha%3A400"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro%3A400%2C600%2C700"/>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins%3A400%2C600"/>
</head>
<body>
    <div class="d-flex justify-content-between align-items-center mx-5 mt-3">
        <div style="width:fit-content; margin: 0 auto;">
            <h1>{{ request.tenant.name }}</h1>
        </div>
        <div class="d-flex justify-content-end align-items-center">
            <div class="user-profile px-3">
                <button class="btn btn-primary dropdown-toggle" style="background-color:hsl(248, 53%, 58%); type="button" id="userProfileDropdown" data-bs-toggle="dropdown" aria-expanded="false">
                  <img src="{% static 'base/assets/user.png' %}" alt="User Profile" style="position:relative; width: 48px; height: 48px;">
                </button>
                
                <!-- Dropdown menu -->
                <ul class="dropdown-menu" aria-labelledby="userProfileDropdown">
                  <li><a class="dropdown-item" href="{% url 'password_change' %}">Reset Password</a></li>
                  <li><hr class="dropdown-divider"></li>
                  <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                </ul>
            </div>
            <div class="d-flex flex-column align-items-start">
                <h5 class="text-end font-weight-bold">{{ bios.user.first_name }} {{ bios.user.last_name }}</h5>
                {% if user.is_student %}
                    <h5 class="text-end text-secondary">Grade: {{ bios.grade }}</h5>
                {% endif %}
            </div>
        </div>
    </div>
    <section class="d-flex justify-content-between m-4 align-items-center">
        <div class="school-image">
            <img src="{% static 'base/assets/redeem-points-1-1.png' %}" class="img-fluid" style="width:60%; height:auto;" alt="redeem-points">
        </div>
        <div class="container-lg" style="background-color:hsl(248, 53%, 58%); border-radius: 24px;">
            <div class="row g-2 justify-content-center align-items-center">
                <div class="col-sm-6 col-lg-6 align-contents-center">
                    <div>
                        <p class="text-light ms-3">{% now "d-m-Y H:i" %}</p>
                        <div class="text-light ms-3">
                            <h3 class="">Welcome back, {{ bios.user.first_name }}</h3>
                            {% if user.is_student %}
                                <p class="">Always stay updated on your points</p>
                            {% elif user.is_teacher %}
                                <p class="">Always stay updated on students points</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
                {% if user.is_student %}
                    <div class="col-sm-3 col-lg-3">
                        <a class="btn p-2 bg-light btn-lg border border-dark" href="{% url 'redeem-point' %}">Redeem Points</a>
                    </div>
                {% elif user.is_teacher %}
                    <div class="col-sm-3 col-lg-3">
                        <a class="btn p-2 bg-light btn-lg border border-dark" href="{% url 'award-point' %}">Award Points</a>
                    </div>
                {% endif %}
                <div class="col-sm-3 col-lg-3 text-center d-none d-md-block">
                    <img src="{% static 'base/assets/redeem-points-1.png' %}" alt="redeem-points" class="img-fluid" style="width:70%; height:auto;">
                </div>
            </div>
        </div>
    </section>
    <section class="d-flex justify-content-between m-3 align-items-start">
        <div class="container text-light mx-4 pt-5 pb-5 justify-content-between align-items-start d-flex flex-column" style="background-color:hsl(248, 53%, 58%); width: 15%; min-width: 50px; height: 565px; border-radius: 24px;">
            {% if user.is_teacher %}
                <a href="{% url 'teachers_dashboard' %}" class="text-decoration-none">
                    <div class="d-flex justify-content-center align-items-center mb-3">
                        <img class="img-fluid me-2" src="{% static 'base/assets/dashboard.png' %}" alt="Dashboard Icon" style="width: 24px; height: 24px">
                        <p class="text-light ml-2 mb-0 d-none d-md-inline">Dashboard</p>
                    </div>
                </a>
                <a href="{% url 'student-points' %}" class="text-decoration-none">
                    <div class="d-flex justify-content-center align-items-center mb-3">
                        <img class="img-fluid me-2" src="{% static 'base/assets/cash.png' %}" alt="Cash Icon" style="width: 24px; height: 24px">
                        <p class="text-light ml-2 mb-0 d-none d-md-inline">Student Points</p>
                    </div>
                </a>
                <a href="{% url 'student-awards' %}" class="text-decoration-none">
                    <div class="d-flex justify-content-center align-items-center mb-3">
                        <img class="img-fluid me-2" src="{% static 'base/assets/notebook.png' %}" alt="Notebook Icon" style="width: 24px; height: 24px">
                        <p class="text-light ml-2 mb-0 d-none d-md-inline">Student Awards</p>
                    </div>
                </a>
                <a href="{% url 'logout' %}" class="text-decoration-none">
                    <div class="d-flex justify-content-center align-items-center">
                        <img class="img-fluid me-2" src="{% static 'base/assets/logout.png' %}" alt="Logout Icon" style="width: 24px; height: 24px">
                        <p class="text-light ml-2 mb-0 d-none d-md-inline">Log Out</p>
                    </div>
                </a>
            {% elif user.is_student %}
                <a href="{% url 'students_dashboard' %}" class="text-decoration-none">
                    <div class="d-flex justify-content-center align-items-center mb-3">
                        <img class="img-fluid me-2" src="{% static 'base/assets/dashboard.png' %}" alt="Dashboard Icon" style="width: 24px; height: 24px">
                        <p class="text-light ml-2 mb-0 d-none d-md-inline">Dashboard</p>
                    </div>
                </a>
                <a href="{% url 'points-awarded' %}" class="text-decoration-none">
                    <div class="d-flex justify-content-center align-items-center mb-3">
                        <img class="img-fluid me-2" src="{% static 'base/assets/cash.png' %}" alt="Cash Icon" style="width: 24px; height: 24px">
                        <p class="text-light ml-2 mb-0 d-none d-md-inline">Points Awarded</p>
                    </div>
                </a>
                <a href="{% url 'points-redeemed' %}" class="text-decoration-none">
                    <div class="d-flex justify-content-center align-items-center mb-3">
                        <img class="img-fluid me-2" src="{% static 'base/assets/notebook.png' %}" alt="Notebook Icon" style="width: 24px; height: 24px">
                        <p class="text-light ml-2 mb-0 d-none d-md-inline">Points Redeemed</p>
                    </div>
                </a>
                <a href="{% url 'logout' %}" class="text-decoration-none">
                    <div class="d-flex justify-content-center align-items-center">
                        <img class="img-fluid me-2" src="{% static 'base/assets/logout.png' %}" alt="Logout Icon" style="width: 24px; height: 24px">
                        <p class="text-light ml-2 mb-0 d-none d-md-inline">Log Out</p>
                    </div>
                </a>
            {% endif %}
        </div>
        <div class="container mt-0">  
            <div class="row align-items-start">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </section>

</body>
</html>

base/templates/base/delete.html
{% extends "base/base.html" %}

{% block title %}Delete Point{% endblock %}

{% block content %}
<!--<form method="post" action="">
  {% csrf_token %}
  <p>Are you sure you want to delete {{obj}}?</p>
  <a href="{{request.META.HTTP_REFERER}}">Go Back</a>
  <input type="submit" value="Confirm" />
</form>-->
<div class="container mt-5">
  <div class="card">
    <div class="card-body">
      <form method="post" action="" class="text-center">
        {% csrf_token %}
        <p class="lead">Are you sure you want to delete <strong>{{ obj }}</strong>?</p>
        <div class="mt-4">
          <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary">Go Back</a>
          <input type="submit" value="Confirm" class="btn btn-danger ml-2">
        </div>
      </form>
    </div>
  </div>
</div>
{% endblock %}

base/templates/base/login.html
{% load static %}
<!DOCTYPE html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'base/assets/favicon-32x32.png' %}">
<title>Login</title>
</head>
  <link rel="stylesheet" type="text/css" href="{% static 'base/css/index.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css"/>
<body>
	<div class="title">
		<h1>Student Point Award System</h1>
	</div>
	<div class="login-box">
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}

			<input type="submit" value="LOGIN">
			<a href="{% url 'reset_password' %}">Forgot password?</a>
		</form>
	</div>
</body>
</html>

base/templates/base/points_awarded.html
{% extends "base/dashboard.html" %}
{% load static %}

{% block title %}Points Awarded{% endblock %}

{% block content %}
<div class="row align-items-start">
    <div class="text-center">
        <h3>Awarded Points</h3>
    </div>
    <form class="form-inline d-flex justify-content-end" method="get" action="{% url 'points-awarded' %}">
        <div class="form-group me-2">
          <input type="text" class="form-control" name="q" placeholder="Search ...">
        </div>
        <button type="submit" class="btn btn-primary me-2">Search</button>
        <button class="btn btn-secondary ml-2" onclick="">Clear</button>
      </form>
    <div class="table-responsive" style="max-height: 480px;">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Category</th>
                <th scope="col">Description</th>
                <th scope="col">Points</th>
            </tr>
            </thead>
            <tbody>
                {% for point in points %}
                    <tr>
                        <td>{{ point.created_at }}</td>
                        <td>{{ point.category.name }}</td>
                        <td>{{ point.description }}</td>
                        <td>{{ point.category.point }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

base/templates/base/points_redeemed.html
{% extends "base/dashboard.html" %}
{% load static %}

{% block title %}Points Redeemed{% endblock %}

{% block content %}
<div class="row align-items-start">
    <div class="text-center">
        <h3>Redeemed Points</h3>
    </div>
    <form class="form-inline d-flex justify-content-end" method="get" action="{% url 'points-awarded' %}">
        <div class="form-group me-2">
          <input type="text" class="form-control" name="q" placeholder="Search ...">
        </div>
        <button type="submit" class="btn btn-primary me-2">Search</button>
        <button class="btn btn-secondary ml-2" onclick="">Clear</button>
      </form>
    <div class="table-responsive" style="max-height: 480px;">
        <table class="table">
            <thead>
            <tr>
                <th scope="col">Date</th>
                <th scope="col">Item</th>
                <th scope="col">Description</th>
                <th scope="col">Points</th>
            </tr>
            </thead>
            <tbody>
                {% for item in items %}
                    <tr>
                        <td>{{ item.date_redeemed }}</td>
                        <td>{{ item.select_award.name }}</td>
                        <td>{{ item.select_award.description }}</td>
                        <td>{{ item.select_award.points }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

base/templates/base/redeem_point.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block title %}Redeem Point{% endblock %}

{% block content %}
<div class="container mt-3" style="width: 50%; font-size: 14px;">
  <div class="text-center">
    <h2 class="text-light">Redeem Point</h2>
  </div>
  <form method="POST" class="card p-3 mt-5" autocomplete="off">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-flex justify-content-between">
      <button type="submit" class="btn btn-outline-primary mt-2" style="width: 90px;">Redeem</button>
      <button class="btn btn-outline-primary mt-2" onclick="goBack()">Back</button>
    </div>
  </form>

  {% for message in messages %}
    {% if message.tags == 'success' %}
      <div class="text-center alert alert-primary alert-dismissible fade show" role="alert">{{message}}
        <a href="{%url 'students_dashboard' %}" type="button" class="btn btn-close" data-bs-dismiss="alert" aria-label="Close"></a>
      </div>
    {% endif %}
  {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script>
  $("#id_select_award").select2({width: '100%'});

  function goBack() {
    window.history.back();
  }
</script>
{% endblock %}